Magic-Capstone/Controllers/CardDecksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Magic_Capstone.Data;
using Magic_Capstone.Models;
using Microsoft.AspNetCore.Identity;
using Magic_Capstone.Models.DeckViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Magic_Capstone.Controllers
{
    public class CardDecksController : Controller
    {
        private readonly ApplicationDbContext _context;

        private Task<ApplicationUser> GetCurrentUserAsync() =>
            _userManager.GetUserAsync(HttpContext.User);

        private readonly UserManager<ApplicationUser> _userManager;

        public CardDecksController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Gets all CardData instances in database and also gets all decks associated with the user
        [Authorize]
        public async Task<IActionResult> CardDeck()
        {
            var currentUser = await GetCurrentUserAsync();
           var userId = currentUser.Id;

            var viewModel = new CardDeckViewModel
            {
                AvailableDecks = await _context.decks.Where(d => d.UserId == userId).ToListAsync(),

            };
            
            viewModel.cardDatas = _context.cardDatas.ToList();
            
            return View(viewModel);
        }


      
        // POST: CardDecks/Create
       //Method to Save CardDatas to the CardDeck join table in order to create decks for the user method does a foreach 
       //with the Ids of the cards in order to allow the user to check multiple cards and save them all at once
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveCard(CardDeck cardDeck, List<int> CardIds)
        {
            string referer = Request.Headers["Referer"].ToString();
            ModelState.Remove("CardDataId");
            if (ModelState.IsValid)
            {
                CardDeckViewModel viewModel = new CardDeckViewModel();

                cardDeck.DeckId = cardDeck.Deck.DeckId;
                
                cardDeck.Deck = null;
                cardDeck.CardData = null;

                viewModel.CardDataIds = CardIds;
                
                
                foreach(var id in CardIds)
                {
                    CardDeck newCard = new CardDeck
                    {
                        DeckId = cardDeck.DeckId,
                        CardDataId = id
                    };
                    _context.Add(newCard);
                };
                
                await _context.SaveChangesAsync();
                
            }
            
            return RedirectToAction("Index", "Decks");
        }


     




        // POST: CardDecks/Delete/5
        //Delete Method that deletes The join table item by its Id
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int CardDeckid)
        {
            string referer = Request.Headers["Referer"].ToString();
            var cardDeck = await _context.cardDecks.FindAsync(CardDeckid);
            _context.cardDecks.Remove(cardDeck);
            await _context.SaveChangesAsync();
            return Redirect(referer);
        }
        public  List<Deck> GetAllDecks()
        {
            List<Deck> decks =  _context.decks.ToList();
            return decks;
        }
        private bool CardDeckExists(int id)
        {
            return _context.cardDecks.Any(e => e.CardDeckId == id);
        }
    }
}

Magic-Capstone/Controllers/CardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Magic_Capstone.Data;
using Magic_Capstone.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Magic_Capstone.Controllers
{
    public class CardsController : Controller
    {
        private readonly ApplicationDbContext _context;

        private Task<ApplicationUser> GetCurrentUserAsync() =>
            _userManager.GetUserAsync(HttpContext.User);

        private readonly UserManager<ApplicationUser> _userManager;

        public CardsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

     
        //Simple Get all method getting all cardData instances in database to display to the user (based on user Id on card)
        // GET: Cards
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.cardDatas.Include(c => c.User);
            return View(await applicationDbContext.ToListAsync());
        }



   

        // POST: Cards/Create
        //Save method for when the user searches the API for cards and clicks on a card the associated card is saved as a CardData item to the Database
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CardId,ConditionId,name,manaCost,type,rarity,text,imageUrl,UserId")] CardData card)
        {
            string referer = Request.Headers["Referer"].ToString();
            ViewData["UserId"] = GetCurrentUserAsync().Id;
            if (ModelState.IsValid)
            {
               var user = await GetCurrentUserAsync();
                card.UserId = user.Id;

                _context.Add(card); 
                await _context.SaveChangesAsync();
                
                
            }
            return Redirect(referer);
            
        }
       

       

       

       
        //Delete method to delete a cardData item by its given ID
        // POST: Cards/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int CardDataid)
        {
            string referer = Request.Headers["Referer"].ToString();
            var card = await _context.cardDatas.FindAsync(CardDataid);
            _context.cardDatas.Remove(card);
            await _context.SaveChangesAsync();
            return Redirect(referer);
        }

        private bool CardExists(int id)
        {
            return _context.cards.Any(e => e.CardId == id);
        }
    }
}

Magic-Capstone/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Magic_Capstone.Models;
using Magic_Capstone.Data;
using Microsoft.AspNetCore.Identity;
using System.Net.Http;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Magic_Capstone.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {

        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public HomeController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

       //Method that takes the string passed into the input field and pings the external api for type based on the string
        public async Task<IActionResult> FindType(string type)
        {
            ApiHelper.InitializeClient();
            string url = $"https://api.magicthegathering.io/v1/cards?type={type}";
            using (HttpResponseMessage response = await ApiHelper.ApiClient.GetAsync(url))
            {
                if (response.IsSuccessStatusCode)
                {
                    var card = await response.Content.ReadAsAsync<Rootobject>();

                    return View(card);
                }
                else
                {
                    throw new Exception(response.ReasonPhrase);
                }
            }

        }
        //Method that takes the string passed into the input field and pings the external api for Name based on the string
        public async Task<IActionResult> FindName(string name)
        {
            ApiHelper.InitializeClient();
            string url = $"https://api.magicthegathering.io/v1/cards?name={name}";
            using (HttpResponseMessage response = await ApiHelper.ApiClient.GetAsync(url))
            {
                if (response.IsSuccessStatusCode)
                {
                    var card = await response.Content.ReadAsAsync<Rootobject>();
              
                    return View(card);
                }
                else
                {
                    throw new Exception(response.ReasonPhrase);
                }
            }

        }
        //Method that takes the string passed into the input field and pings the external api for color based on the string
        public async Task<IActionResult> FindColor(string color)
        {
            ApiHelper.InitializeClient();
            string url = $"https://api.magicthegathering.io/v1/cards?colors={color}";
            using (HttpResponseMessage response = await ApiHelper.ApiClient.GetAsync(url))
            {
                if (response.IsSuccessStatusCode)
                {
                    var card = await response.Content.ReadAsAsync<Rootobject>();

                    return View(card);
                }
                else
                {
                    throw new Exception(response.ReasonPhrase);
                }
            }
        }

        //Method to get the last 20 cards added to the database and displays them on the home page under the search bars
        public async Task<IActionResult> Index()
        {

            var currentuser = await GetCurrentUserAsync();
           
                var userId = currentuser.Id;

            var applicationDbContext = _context.cardDatas
                    .Where(cd => cd.UserId == userId)
                    .Take(20);

                return View(await applicationDbContext.ToListAsync());
           
        }







        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Magic-Capstone/Views/Home/FindColor.cshtml
@model Magic_Capstone.Models.Rootobject


@{
    ViewData["Title"] = "FindColor";
}

<link rel="stylesheet" href="~/css/TaskCardStyle.css">

<h1 class="centerCards">Find By Color</h1>
<h4 class="centerCards">If you wish to save a card simply click on it!</h4>

<div class="cardflex">

    @foreach (var item in Model.cards)
    {
        if (item.imageUrl != null)
        {
            <form asp-action="Create" asp-controller="Cards">


                

                <div class="cardInfo">
                    @Html.Hidden("name", item.name)
                    @Html.Hidden("type", item.type)
                    @Html.Hidden("text", item.text)
                    @Html.Hidden("colors", item.colors)
                    @Html.Hidden("manaCost", item.manaCost)
                    @Html.Hidden("imageUrl", item.imageUrl)
                    @Html.Hidden("rarity", item.rarity)
                    <div class="form-group">
                        <input type="image" src=@item.imageUrl id="magic"/>
                    </div>
                </div>
            </form>
        }
    }
</div>
<a asp-action="Index" class="btn btn-dark">Back to HomePage</a>

Magic-Capstone/Views/Home/FindName.cshtml
@model Magic_Capstone.Models.Rootobject
@{
    ViewData["Title"] = "FindName";
}



<link rel="stylesheet" href="~/css/TaskCardStyle.css">
<h1 class="centerCards">Find By Name</h1>
<h4 class="centerCards">If you wish to save a card simply click on it!</h4>
<div class="cardflex">


    @foreach (var item in Model.cards)
    {
        if (item.imageUrl != null)
        {

            <form asp-action="Create" asp-controller="Cards">


                

                <div class="cardInfo">
                    @Html.Hidden("name", item.name)
                    @Html.Hidden("type", item.type)
                    @Html.Hidden("text", item.text)
                    @Html.Hidden("colors", item.colors)
                    @Html.Hidden("manaCost", item.manaCost)
                    @Html.Hidden("imageUrl", item.imageUrl)
                    @Html.Hidden("rarity", item.rarity)
                    <div class="form-group">
                        <input type="image" src=@item.imageUrl id="magic"/>
                    </div>
                </div>
            </form>

        }
    }
</div>
<a asp-action="Index" class="btn btn-dark">Back to HomePage</a>

Magic-Capstone/Views/Home/FindType.cshtml
@model Magic_Capstone.Models.Rootobject

@{
    ViewData["Title"] = "FindType";
}
    <link rel="stylesheet" href="~/css/TaskCardStyle.css">
<h1 class="centerCards">Find By Type</h1>
<h4 class="centerCards">If you wish to save a card simply click on it!</h4>

<div class="cardflex">


    @foreach (var item in Model.cards)
    {
        if (item.imageUrl != null)
        {

    <form asp-action="Create" asp-controller="Cards">


        

        <div class="cardInfo">
            @Html.Hidden("name", item.name)
            @Html.Hidden("type", item.type)
            @Html.Hidden("text", item.text)
            @Html.Hidden("colors", item.colors)
            @Html.Hidden("manaCost", item.manaCost)
            @Html.Hidden("imageUrl", item.imageUrl)
            @Html.Hidden("rarity", item.rarity)
            <div class="form-group">
                <input type="image" src=@item.imageUrl id="magic"/>
            </div>
        </div>
    </form>
        }
    }

</div>
<a asp-action="Index" class="btn btn-dark">Back to HomePage</a>

Magic-Capstone/Views/Home/Index.cshtml
@model IEnumerable<Magic_Capstone.Models.CardData>
    @{
        ViewData["Title"] = "Index";
    }
 
        <link rel="stylesheet" href="~/css/HomeStyle.css">
        <link rel="stylesheet" href="~/css/TaskCardStyle.css">

        <h1>Magical Search!</h1>

        <div class="flexClass">
            <form>
                <p class="onTop">
                    <input type="text" name="type" class="searchBox">
                    <input type="submit" value="Search By Type" asp-action="FindType" class="btn btn-dark" />
                </p>
            </form>

            <form>
                <p class="onTop">
                    <input type="text" name="name" class="searchBox">
                    <input type="submit" value="Search By Name" asp-action="FindName" class="btn btn-dark" />

                </p>
            </form>

            <form>
                <p class="onTop">
                    <input type="text" name="color" class="searchBox">
                    <input type="submit" value="Search By Color" asp-action="FindColor" class="btn btn-dark" />
                </p>
            </form>
        </div>
        <a asp-action="Create" asp-controller="Decks" class="btn btn-dark">Create New Deck</a>
        <a asp-action="CardDeck" asp-controller="CardDecks" class="btn btn-dark" id="UpdateCurrent">Update Current Decks</a>

            <h2>Recent Cards</h2>

        <div class="centerCards, cardflex">

            @foreach (var item in Model)
            {
                
                 <img class="img-responsive" src=@item.imageUrl id="magic" />
                   
                    }

            </div>
   